<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="staging"
    errors="0" failures="1" hostname="" id="" package="staging" skipped="0"
    tests="1" time="4.336" timestamp="Thu, 24 Dec 2015 22:58:05 GMT">
  
    <testcase name="Staging is up and running" time="4.336" assertions="1">  <failure message="Testing if the URL equals &quot;http://staging.tallyspot.com/&quot;.">    at Object.testStaging [as Staging is up and running] (/Users/rhughes1/Sites/tallyspot/tests/scripts/staging.js:9:15)
    at Module.call (/Users/rhughes1/Sites/tallyspot/tests/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/rhughes1/Sites/tallyspot/tests/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/rhughes1/Sites/tallyspot/tests/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/rhughes1/Sites/tallyspot/tests/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/rhughes1/Sites/tallyspot/tests/node_modules/q/q.js:796:13)
    at /Users/rhughes1/Sites/tallyspot/tests/node_modules/q/q.js:556:49
    at runSingle (/Users/rhughes1/Sites/tallyspot/tests/node_modules/q/q.js:137:13)
    at flush (/Users/rhughes1/Sites/tallyspot/tests/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:433:9)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
